name = "telegram-cloud-vault"
main = "worker.js"
compatibility_date = "2025-03-01"

[[kv_namespaces]]
binding = "easycloud"
id = "9a3d8edafc324885b99ab20b5b3619f0"

[vars]
TELEGRAM_CHAT_ID = "7183111659"
