name = "easycloud"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "easycloud"
id = "9a3d8edafc324885b99ab20b5b3619f0"

[vars]
TELEGRAM_CHAT_ID = "7183111659"

# Set BOT_TOKEN as a secret:
# wrangler secret put BOT_TOKEN
